name: "Codespell"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install codespell
      run: |
        sudo apt-get update
        sudo apt-get install codespell

    - name: Perform spelling checks
      run: README.md RELEASE-NOTES trurl.c CONTRIBUTING.md trurl.1 trurl.c
